CREATE TABLE CUSTOMER (
  ID INT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(255) NOT NULL,
  EMAIL VARCHAR(255) NOT NULL,
  CONSTRAINT CUSTOMER_PK PRIMARY KEY (ID),
  CONSTRAINT CUSTOMER_EMAIL_UN UNIQUE (EMAIL)
);
