CREATE TABLE BOOK (
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  TITLE VARCHAR(255) NOT NULL,
  PRICE DECIMAL(19, 2) NOT NULL,
  STATUS VARCHAR(255) NOT NULL,
  CUSTOMER_ID INT NOT NULL
);
ALTER TABLE BOOK ADD CONSTRAINT CUSTOMER_BOOK_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID);