CREATE TABLE PURCHASE (
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  CUSTOMER_ID INT NOT NULL,
  NFE VARCHAR(255),
  PRICE DECIMAL(15, 2) NOT NULL,
  CREATED_AT TIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP NULL);
ALTER TABLE PURCHASE ADD CONSTRAINT CUSTOMER_PURCHASE_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID);

CREATE TABLE PURCHASE_BOOK (
  PURCHASE_ID INT NOT NULL,
  BOOK_ID INT NOT NULL,
  CONSTRAINT PURCHASE_BOOK_PK PRIMARY KEY (PURCHASE_ID, BOOK_ID)
);
ALTER TABLE PURCHASE_BOOK ADD CONSTRAINT PURCHASE_BOOK_FK FOREIGN KEY (PURCHASE_ID) REFERENCES PURCHASE(ID);
ALTER TABLE PURCHASE_BOOK ADD CONSTRAINT BOOK_PURCHASE_FK FOREIGN KEY (BOOK_ID) REFERENCES BOOK(ID);
