CREATE TABLE CUSTOMER_ROLES (
  CUSTOMER_ID INT NOT NULL,
  ROLE VARCHAR(255) NOT NULL
);
ALTER TABLE CUSTOMER_ROLES ADD CONSTRAINT CUSTOMER_ROLES_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID);

